### ISSUE TITLE
Suggestion: Add languages you would use on a slide.

### ISSUE THREAD

**Issue by PritamSangani** [YusofBandar/CS50-Event#3]
A suggestion only - maybe you could put the languages used on a slide or even a week-by-week list of problem-set domains so people get an idea of how wide Computer Science problems range and what fields you would get exposure in within the course.

**Comment by YusofBandar** [comment]
[CS50 Presentation](https://github.com/YusofBandar/CS50-Event/blob/master/Welcome%20Event/Welcome%20Event%20Presentation.pdf) Slide 3 Provides all the necessary information about the course
